# Generated by Django 4.2.6 on 2023-12-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='title',
        ),
    ]
